# Generated by Django 2.2.24 on 2021-08-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=2000)),
                ('singer', models.CharField(max_length=2000)),
                ('tags', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='documents')),
                ('song', models.FileField(upload_to='documents')),
            ],
        ),
    ]
